[package]
name = "drop-script"
version = "0.1.0"
edition = "2021"

[dependencies]
maenad-sdk = { path = "../sdk" }
anyhow = "1.0.100"
ethers = { version = "2.0.14", features = ["rustls"] }
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
storage = { path = "../storage" }
drop-lib = { path = "../drop-lib" }
blake3 = "1.8.2"
sp1-sdk = { version = "6.2.4", features = ["network"] }
serde = "1.0.203"
serde_json = "1.0.117"
sha2 = "0.10.8"
reqwest = "0.12.2"
hex = "0.4"
