[package]
name = "maenad"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "maenad-lib",
    "guest/*/script",
    "guest/*/program",
    "core",
    "client/gui/src-tauri",
    "storage",
    "walrus-core",
]

[workspace.dependencies]
alloy-sol-types = "1.0"

[dependencies]
maenad_gui = { path = "client/gui/src-tauri" }

[lib]
name = "core"
path = "core/src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "maenad_gui"
path = "client/gui/src-tauri/src/main.rs"
