[package]
version = "0.1.0"
name = "program-vdd-walrus-rslhve"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "6.0.2"
vdd-lib = { path = "../lib" }
blake3 = "1.8.2"
drop-lib = { path = "../../../drop-lib", default-features = false, features = ["guest"] }
hex = "0.4.3"
sha2 = "0.10.9"
