[package]
version = "0.1.0"
name = "vdd-script"
edition = "2021"
default-run = "vdd_filecoin"

[[bin]]
name = "vdd_filecoin"
path = "src/bin/main_filecoin.rs"

[[bin]]
name = "vdd_walrus"
path = "src/bin/main_walrus.rs"

[[bin]]
name = "evm_filecoin"
path = "src/bin/evm_filecoin.rs"

[[bin]]
name = "evm_walrus"
path = "src/bin/evm_walrus.rs"

[[bin]]
name = "vkey_filecoin"
path = "src/bin/vkey_filecoin.rs"

[[bin]]
name = "vkey_walrus"
path = "src/bin/vkey_walrus.rs"

[dependencies]
sp1-sdk = "5.0.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
vdd-lib = { path = "../lib" }
dotenv = "0.15.0"
maenad-lib = { path = "../../../maenad-lib" }
blake3 = "1.8.2"
rand = "0.9.2"
cid = "0.11"

[build-dependencies]
sp1-build = "5.0.8"
