[package]
version = "0.1.0"
name = "vdd-script"
edition = "2021"
default-run = "vdd_filecoin"

[[bin]]
name = "vdd_filecoin"
path = "src/bin/main_filecoin.rs"

[[bin]]
name = "vdd_walrus"
path = "src/bin/main_walrus.rs"

[[bin]]
name = "main_walrus_rslhve"
path = "src/bin/main_walrus_rslhve.rs"

[[bin]]
name = "evm_filecoin"
path = "src/bin/evm_filecoin.rs"

[[bin]]
name = "evm_walrus"
path = "src/bin/evm_walrus.rs"

[[bin]]
name = "evm_walrus_rslhve"
path = "src/bin/evm_walrus_rslhve.rs"

[[bin]]
name = "pn_walrus_rslhve"
path = "src/bin/pn_walrus_rslhve.rs"

[[bin]]
name = "vkey_filecoin"
path = "src/bin/vkey_filecoin.rs"

[[bin]]
name = "vkey_walrus"
path = "src/bin/vkey_walrus.rs"

[[bin]]
name = "vkey_walrus_rslhve"
path = "src/bin/vkey_walrus_rslhve.rs"

[dependencies]
sp1-sdk = { version = "6.2.4", features = ["network"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
vdd-lib = { path = "../lib" }
dotenv = "0.15.0"
drop-lib = { path = "../../../drop-lib" }
blake3 = "1.8.2"
rand = "0.9.2"
cid = "0.11"
sha2 = "0.10.9"
chacha20 = "0.9.1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
sp1-build = "6.2.4"
