[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[features]
default = []
std-io = ["multihash/std", "cid/std"]

[dependencies]
alloy-sol-types = { workspace = true }
blake3 = "1.8.2"
sp1-lib = "5.2.2"
sp1-zkvm = { version = "5.0.8" }
k256 = { version = "0.13", default-features = false, features = ["arithmetic"] }
chacha20 = "0.9.1"
sha256 = "1.6.0"
sha2 = "0.10.9"
hex = "0.4.3"
ipfs-unixfs = "0.2.0"
multihash = "0.19.3"
cid = "0.11.1"
libipld-core = "0.16.0"
