[package]
version = "0.1.0"
name = "program-vdd-walrus"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.8"
vdd-lib = { path = "../lib" }
blake3 = "1.8.2"
maenad-lib = { path = "../../../maenad-lib", default-features = false, features = ["guest"] }
hex = "0.4.3"