#!/usr/bin/env bash
set -euo pipefail

BASE_ENV="${DROP_CLI_BASE_ENV_FILE:-drop-script/.env}"
RUNTIME_ENV="${DROP_CLI_RUNTIME_ENV:-/tmp/trustdrop-drop-cli.env}"
WALRUS_ENDPOINT="${TRUSTDROP_CONTAINER_WALRUS_ENDPOINT:-http://walrus-publisher:31415}"

if [ ! -s "$BASE_ENV" ]; then
  echo "missing drop-cli base env: $BASE_ENV" >&2
  exit 2
fi

mkdir -p "$(dirname -- "$RUNTIME_ENV")"
grep -v -E "^(WALRUS_LOCAL_ENDPOINT|WALRUS_PUBLISHER_URL)=" "$BASE_ENV" > "$RUNTIME_ENV"
{
  printf '\n# Runtime container overrides; generated by docker/seller/run-drop-cli-in-container.sh\n'
  printf 'WALRUS_LOCAL_ENDPOINT=%s\n' "$WALRUS_ENDPOINT"
  printf 'WALRUS_PUBLISHER_URL=%s\n' "$WALRUS_ENDPOINT"
} >> "$RUNTIME_ENV"
chmod 600 "$RUNTIME_ENV" 2>/dev/null || true
export DROP_CLI_ENV="$RUNTIME_ENV"

exec target/debug/drop-cli "$@"
